services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
      - '8081:81'
    environment:
      TZ: "Australia/Brisbane"
    volumes:
      - ./volumes/npm_data/data:/data
      - ./volumes/npm_data/letsencrypt:/etc/letsencrypt
